#!/bin/bash
if [ "$1" = "-s" ]; then
    if [ "$4" != "" ]; then
        java -jar cc0.jar -s $2>$4
        cat $4
    else
        java -jar cc0.jar -s $2
    fi
elif [ "$1" = "-c" ]; then
    if [ "$4" != "" ]; then
        java -jar cc0.jar -s $2>_temp.s
        cat _temp.s
        ./c0-vm-cpp -a _temp.s $4
        rm -f _temp.s
    else
        java $1 $2 $3 $4
    fi
else
    java $1 $2 $3 $4
fi

